# Generated by Django 4.1 on 2023-02-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='certificate/')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('fullname', models.CharField(max_length=225)),
                ('role', models.CharField(max_length=225)),
                ('organization', models.CharField(default='Kartexa', max_length=255)),
                ('internship_organizer', models.CharField(max_length=225)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('issue_date', models.DateTimeField()),
                ('verification_link', models.URLField(blank=True, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcode')),
            ],
        ),
    ]
