# Generated by Django 4.1 on 2023-02-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_certificate_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
